import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Header from "./components/Header";
import Home from "./components/Home";
async function fetchALLFeedbacks() {
  const res = await fetch(`http://localhost:3000/api/feedback`);
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Header />
        {children}
        <Home />
      </body>
    </html>
  );
}
